name: Deploy Python App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mail-forwarder-to-tg:latest .

      - name: Save Docker image to tar
        run: docker save mail-forwarder-to-tg:latest -o mail-forwarder-to-tg.img

      - name: Copy image to server
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: ./mail-forwarder-to-tg.img
          remote_path: ~/mail-forwarder-to-tg.img
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load -i ~/mail-forwarder-to-tg.img
            docker stop mail-forwarder-to-tg || true
            docker rm mail-forwarder-to-tg || true

            docker run -d \
              --name mail-forwarder-to-tg \
              --restart always \
              -e TG_BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}" \
              -e DOMAIN="${{ secrets.DOMAIN }}" \
              -p 25:25 \
              mail-forwarder-to-tg:latest
            
            rm ~/mail-forwarder-to-tg.img